"use client";

import { Card } from "@/components/common/Card";
import { useAuth } from "@/lib/auth/AuthContext";

export function AdminShell() {
  const { admin } = useAuth();
  return <div><header className="mb-6 rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm font-semibold uppercase tracking-wide text-blue-700">Secure admin dashboard</p><h1 className="mt-1 text-2xl font-bold text-slate-950">Welcome{admin?.displayName ? `, ${admin.displayName}` : ""}</h1><p className="mt-2 text-sm text-slate-600">You are signed in as an active admin. Jobs are the only CMS module implemented in Phase 3.</p></header><div className="grid gap-4 md:grid-cols-3"><Card><p className="text-sm text-slate-500">Jobs module</p><p className="mt-2 text-3xl font-bold">Ready</p></Card><Card><p className="text-sm text-slate-500">Role</p><p className="mt-2 text-2xl font-bold">{admin?.role}</p></Card><Card><p className="text-sm text-slate-500">Security</p><p className="mt-2 text-2xl font-bold">Protected</p></Card></div></div>;
}
import Link from "next/link";
import { Card } from "@/components/common/Card";
const adminNav = ["Dashboard", "Jobs", "Exams", "Results", "Admit Cards", "Answer Keys", "Universities", "Organizations", "Categories", "States", "Ads", "Site Settings", "Audit Logs"];
export function AdminShell() { return <div className="min-h-screen bg-slate-100"><div className="grid lg:grid-cols-[280px_1fr]"><aside className="border-r border-slate-200 bg-white p-5"><Link href="/" className="font-bold text-blue-800">Government Career Portal</Link><nav className="mt-6 grid gap-1" aria-label="Admin navigation">{adminNav.map((item) => <a key={item} href="#" className="rounded-lg px-3 py-2 text-sm font-medium text-slate-700 hover:bg-blue-50">{item}</a>)}</nav></aside><main className="p-4 sm:p-6 lg:p-8"><header className="mb-6 rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm font-semibold uppercase tracking-wide text-blue-700">Admin foundation</p><h1 className="mt-1 text-2xl font-bold text-slate-950">Dashboard shell</h1><p className="mt-2 text-sm text-slate-600">Authentication, role checks, CRUD forms and audit logging will be completed in later phases. Firestore rules must enforce authorization before production use.</p></header><div className="grid gap-4 md:grid-cols-3"><Card><p className="text-sm text-slate-500">Jobs</p><p className="mt-2 text-3xl font-bold">0</p></Card><Card><p className="text-sm text-slate-500">Published</p><p className="mt-2 text-3xl font-bold">0</p></Card><Card><p className="text-sm text-slate-500">Admin actions</p><p className="mt-2 text-3xl font-bold">0</p></Card></div></main></div></div>; }
